package com.turbomesh.desktop.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Tabs
    val tabMessaging: String,
    val tabDevices: String,
    val tabNetwork: String,
    val tabSettings: String,
    val tabPacketLog: String,
    val tabTopology: String,
    // Messaging
    val everyone: String,
    val everyoneBroadcast: String,
    val toLabel: String,
    val messagePlaceholder: String,
    val send: String,
    val update: String,
    val emergency: String,
    val search: String,
    val close: String,
    val pinned: String,
    val export: String,
    val noMessages: String,
    val noMessagesMatch: String,
    val searchMessages: String,
    val clearLabel: String,
    val pinnedMessages: String,
    val results: String,
    val result: String,
    val forText: String,
    val replyingTo: String,
    val editingMessage: String,
    val cancel: String,
    val reply: String,
    val react: String,
    val edit: String,
    val pin: String,
    val unpin: String,
    val delete: String,
    val isTyping: String,
    val areTyping: String,
    val schedule: String,
    val attachFile: String,
    val voiceNote: String,
    val seenBy: String,
    val scheduleMessage: String,
    val scheduleDate: String,
    val scheduleTime: String,
    val confirm: String,
    val pendingScheduled: String,
    val fileAttached: String,
    val voiceRecording: String,
    val playVoice: String,
    val stopVoice: String,
    // Devices
    val bleDevices: String,
    val devicesFound: String,
    val deviceFound: String,
    val stopScan: String,
    val scan: String,
    val clearDevices: String,
    val scanFailed: String,
    val dismiss: String,
    val scanningForDevices: String,
    val pressScanPrompt: String,
    val requiresBluetooth: String,
    val nickname: String,
    val rename: String,
    val ping: String,
    val wave: String,
    val setNickname: String,
    val save: String,
    val battery: String,
    val pair: String,
    // Network
    val networkOverview: String,
    val sent: String,
    val received: String,
    val nearby: String,
    val ble: String,
    val bridgeRelay: String,
    val connected: String,
    val disconnected: String,
    val bridgeDisabled: String,
    val disconnect: String,
    val connect: String,
    val visibleNodes: String,
    val found: String,
    val noNodesVisible: String,
    val lastSeen: String,
    val readings: String,
    val localNode: String,
    val rssiChart: String,
    // Packet Log
    val packetLogTitle: String,
    val clearLog: String,
    val filterAll: String,
    val filterInbound: String,
    val filterOutbound: String,
    val noPackets: String,
    val bytes: String,
    val hops: String,
    // Topology
    val topologyTitle: String,
    val refreshLayout: String,
    val showLabels: String,
    val noTopology: String,
    // Settings
    val settingsTitle: String,
    val meshProtocol: String,
    val defaultTtl: String,
    val heartbeatInterval: String,
    val maxReconnectAttempts: String,
    val messageRetries: String,
    val security: String,
    val e2eEncryption: String,
    val e2eSubtitle: String,
    val bridge: String,
    val enableBridge: String,
    val bridgeSubtitle: String,
    val bridgeServerUrl: String,
    val bridgePlaceholder: String,
    val appearance: String,
    val darkTheme: String,
    val darkThemeSubtitle: String,
    val autoLock: String,
    val enableAutoLock: String,
    val autoLockSubtitle: String,
    val autoLockTimeout: String,
    val setPin: String,
    val changePin: String,
    val clearPin: String,
    val language: String,
    val exportAll: String,
    val exportAllSubtitle: String,
    val exportedTo: String,
    val appVersion: String,
    val appSubtitle: String,
    val minutes: String,
    val enterPin: String,
    val confirmPin: String,
    val pinsDoNotMatch: String,
    val pinSet: String,
    val wrongPin: String,
    val attemptsRemaining: String,
    val unlockApp: String,
    // Pairing
    val pairingTitle: String,
    val pairingStep1: String,
    val pairingStep2: String,
    val pairingStep3: String,
    val pairingPin: String,
    val peerPublicKey: String,
    val peerKeyPlaceholder: String,
    val pairingSuccess: String,
    val pairingConfirm: String,
    val myPublicKey: String,
    val copyKey: String,
    val copied: String,
    val derivePin: String,
    val pairingVerifyHint: String,
    val shareClipboard: String,
    val clipboardSent: String,
    val fileAttachLabel: String,
    val fileReceived: String,
    val showInFolder: String,
    val clipboardMessage: String,
    val copyToClipboard: String,
    // Groups
    val groups: String,
    val newGroup: String,
    val groupName: String,
    val groupMembers: String,
    val createGroup: String,
    val deleteGroup: String,
    val groupInviteSent: String,
    val noGroupsYet: String,
    val groupChat: String,
    // Scheduling
    val scheduleAt: String,
    val scheduledFor: String,
    val invalidDateTime: String,
    val datePlaceholder: String,
    val timePlaceholder: String,
    // Expiry
    val messageExpiry: String,
    val noExpiry: String,
    val expiry1h: String,
    val expiry24h: String,
    val expiry7d: String,
    // Read receipts
    val seenByCount: String,
    // Presence
    val online: String,
    val idle: String,
    val offline: String,
    // Bulk ops
    val markAllRead: String,
    val clearConversation: String,
    val conversationCleared: String,
    // Stars
    val star: String,
    val unstar: String,
    val starred: String,
    val starredMessages: String,
    val noStarredMessages: String,
    // Mute
    val muteConversation: String,
    val unmuteConversation: String,
    val muted: String,
    // Status
    val userStatus: String,
    val statusAvailable: String,
    val statusAway: String,
    val statusBusy: String,
    val statusDnd: String,
    // Notifications
    val soundNotifications: String,
    val soundNotificationsSubtitle: String,
    // Font scale
    val fontScale: String,
    // Forwarding
    val forward: String,
    val forwardTo: String,
    val forwarded: String,
    // Quick replies
    val quickReplies: String,
    val quickRepliesHint: String,
    // Auto-reply
    val autoReply: String,
    val autoReplySubtitle: String,
    val autoReplyMessage: String,
    val autoReplyMessageLabel: String,
    // Node notes
    val notes: String,
    val notesPlaceholder: String,
    val noteSaved: String,
    // Conversations sidebar
    val conversations: String,
    val lastMessage: String,
    val noConversations: String,
)

val EnglishStrings = AppStrings(
    tabMessaging = "Messaging", tabDevices = "Devices", tabNetwork = "Network",
    tabSettings = "Settings", tabPacketLog = "Packet Log", tabTopology = "Topology",
    everyone = "Everyone", everyoneBroadcast = "Everyone (Broadcast)", toLabel = "To:",
    messagePlaceholder = "Message… (Enter to send, Shift+Enter newline)",
    send = "Send", update = "Update", emergency = "Emergency", search = "Search",
    close = "Close", pinned = "Pinned", export = "Export", noMessages = "No messages yet — send something!",
    noMessagesMatch = "No messages match", searchMessages = "Search messages…", clearLabel = "Clear",
    pinnedMessages = "📌 Pinned Messages", results = "results", result = "result", forText = "for",
    replyingTo = "Replying to:", editingMessage = "Editing message", cancel = "Cancel",
    reply = "Reply", react = "React", edit = "Edit", pin = "Pin", unpin = "Unpin", delete = "Delete",
    isTyping = "is typing…", areTyping = "are typing…", schedule = "Schedule", attachFile = "Attach File",
    voiceNote = "Voice Note", seenBy = "Seen by", scheduleMessage = "Schedule Message",
    scheduleDate = "Date (YYYY-MM-DD)", scheduleTime = "Time (HH:MM)", confirm = "Confirm",
    pendingScheduled = "⏰ Scheduled", fileAttached = "📎 File", voiceRecording = "Recording…",
    playVoice = "▶ Play", stopVoice = "■ Stop",
    bleDevices = "BLE Devices", devicesFound = "devices found", deviceFound = "device found",
    stopScan = "Stop", scan = "Scan", clearDevices = "Clear", scanFailed = "Scan failed",
    dismiss = "Dismiss", scanningForDevices = "Scanning for mesh devices…",
    pressScanPrompt = "Press Scan to discover nearby BLE devices",
    requiresBluetooth = "Requires Bluetooth adapter + BlueZ running",
    nickname = "Nickname", rename = "Rename", ping = "Ping", wave = "Wave",
    setNickname = "Set Nickname", save = "Save", battery = "Battery", pair = "Pair…",
    networkOverview = "Network Overview", sent = "Sent", received = "Received",
    nearby = "Nearby", ble = "BLE", bridgeRelay = "Bridge Relay", connected = "● Connected to",
    disconnected = "○ Disconnected", bridgeDisabled = "Bridge disabled",
    disconnect = "Disconnect", connect = "Connect", visibleNodes = "Visible Nodes",
    found = "found", noNodesVisible = "No nodes visible — scan from Devices tab",
    lastSeen = "Last seen:", readings = "readings", localNode = "Local Node", rssiChart = "RSSI",
    packetLogTitle = "Packet Log", clearLog = "Clear", filterAll = "All",
    filterInbound = "Inbound", filterOutbound = "Outbound", noPackets = "No packets captured yet.",
    bytes = "B", hops = "hops",
    topologyTitle = "Mesh Topology", refreshLayout = "Refresh", showLabels = "Labels",
    noTopology = "No nodes visible — scan from Devices tab",
    settingsTitle = "Settings", meshProtocol = "Mesh Protocol", defaultTtl = "Default TTL",
    heartbeatInterval = "Heartbeat interval", maxReconnectAttempts = "Max reconnect attempts",
    messageRetries = "Message retries", security = "Security",
    e2eEncryption = "End-to-End Encryption", e2eSubtitle = "ECDH P-256 + AES-256-GCM",
    bridge = "Bridge", enableBridge = "Enable Bridge",
    bridgeSubtitle = "Forward packets via WebSocket relay",
    bridgeServerUrl = "Bridge Server URL", bridgePlaceholder = "ws://localhost:8080/relay",
    appearance = "Appearance", darkTheme = "Dark Theme", darkThemeSubtitle = "Toggle between light and dark",
    autoLock = "Auto-Lock", enableAutoLock = "Enable Auto-Lock",
    autoLockSubtitle = "Lock app after inactivity",
    autoLockTimeout = "Lock after", setPin = "Set PIN", changePin = "Change PIN",
    clearPin = "Clear PIN", language = "Language", exportAll = "Export All Conversations",
    exportAllSubtitle = "Dump all messages to a text file",
    exportedTo = "Exported to", appVersion = "TurboMesh Desktop v1.1.0",
    appSubtitle = "Compose Multiplatform • BLE Mesh over BlueZ",
    minutes = "min", enterPin = "Enter PIN", confirmPin = "Confirm PIN",
    pinsDoNotMatch = "PINs do not match", pinSet = "PIN set successfully",
    wrongPin = "Incorrect PIN", attemptsRemaining = "attempts remaining",
    unlockApp = "Unlock TurboMesh",
    pairingTitle = "Key Pairing", pairingStep1 = "1. Share your public key",
    pairingStep2 = "2. Enter peer's public key (hex/Base64)",
    pairingStep3 = "3. Verify pairing PIN matches on both devices",
    pairingPin = "Pairing PIN:", peerPublicKey = "Peer Public Key",
    peerKeyPlaceholder = "Paste Base64 key…", pairingSuccess = "✓ Paired!",
    pairingConfirm = "Confirm Pair", myPublicKey = "My Public Key",
    copyKey = "Copy Key", copied = "Copied!",
    derivePin = "Derive PIN",
    pairingVerifyHint = "Verify this PIN matches on the peer device before confirming.",
    shareClipboard = "Share Clipboard",
    clipboardSent = "Clipboard sent",
    fileAttachLabel = "Attach File",
    fileReceived = "File received",
    showInFolder = "Show in Folder",
    clipboardMessage = "Clipboard",
    copyToClipboard = "Copy",
    // Groups
    groups = "Groups", newGroup = "New Group", groupName = "Group Name",
    groupMembers = "Members", createGroup = "Create Group",
    deleteGroup = "Delete Group", groupInviteSent = "Group invite sent",
    noGroupsYet = "No groups yet — create one!", groupChat = "Group",
    // Scheduling
    scheduleAt = "Schedule", scheduledFor = "Scheduled for",
    invalidDateTime = "Invalid date/time — use YYYY-MM-DD HH:MM",
    datePlaceholder = "YYYY-MM-DD", timePlaceholder = "HH:MM",
    // Expiry
    messageExpiry = "Expires", noExpiry = "Never", expiry1h = "1 hour",
    expiry24h = "24 hours", expiry7d = "7 days",
    // Read receipts
    seenByCount = "Seen",
    // Presence
    online = "Online", idle = "Idle", offline = "Offline",
    // Bulk ops
    markAllRead = "Mark all read", clearConversation = "Clear conversation",
    conversationCleared = "Conversation cleared",
    // Stars
    star = "Star", unstar = "Unstar", starred = "Starred",
    starredMessages = "⭐ Starred Messages", noStarredMessages = "No starred messages",
    // Mute
    muteConversation = "Mute", unmuteConversation = "Unmute", muted = "🔇 Muted",
    // Status
    userStatus = "My Status", statusAvailable = "Available",
    statusAway = "Away", statusBusy = "Busy", statusDnd = "Do Not Disturb",
    // Notifications
    soundNotifications = "Sound Notifications",
    soundNotificationsSubtitle = "Play a sound when messages arrive",
    // Font scale
    fontScale = "Font Scale",
    // Forwarding
    forward = "Forward", forwardTo = "Forward to…", forwarded = "↩ Forwarded",
    // Quick replies
    quickReplies = "Quick Replies",
    quickRepliesHint = "Pipe-separated shortcuts, e.g. Hello|OK|On my way",
    // Auto-reply
    autoReply = "Auto-Reply", autoReplySubtitle = "Send auto-reply when Away or DND",
    autoReplyMessage = "I'm currently away. I'll get back to you soon.",
    autoReplyMessageLabel = "Auto-reply text",
    // Node notes
    notes = "Notes", notesPlaceholder = "Private notes about this node…", noteSaved = "Note saved",
    // Conversations sidebar
    conversations = "Conversations", lastMessage = "No messages yet",
    noConversations = "No conversations yet",
)

val SpanishStrings = EnglishStrings.copy(
    // Tabs
    tabMessaging = "Mensajes", tabDevices = "Dispositivos", tabNetwork = "Red",
    tabSettings = "Ajustes", tabPacketLog = "Registro", tabTopology = "Topología",
    // Messaging
    everyone = "Todos", everyoneBroadcast = "Todos (Difusión)", toLabel = "Para:",
    messagePlaceholder = "Mensaje… (Enter para enviar, Shift+Enter nueva línea)",
    send = "Enviar", update = "Actualizar", emergency = "Emergencia",
    search = "Buscar", close = "Cerrar", pinned = "Fijados", export = "Exportar",
    noMessages = "Sin mensajes — ¡envía algo!", noMessagesMatch = "Sin coincidencias",
    searchMessages = "Buscar mensajes…", clearLabel = "Limpiar",
    pinnedMessages = "📌 Mensajes fijados", replyingTo = "Respondiendo a:",
    editingMessage = "Editando mensaje", cancel = "Cancelar",
    reply = "Responder", react = "Reaccionar", edit = "Editar",
    pin = "Fijar", unpin = "Desfijar", delete = "Eliminar",
    isTyping = "está escribiendo…", areTyping = "están escribiendo…",
    // Devices
    bleDevices = "Dispositivos BLE", devicesFound = "dispositivos encontrados",
    deviceFound = "dispositivo encontrado", stopScan = "Detener", scan = "Escanear",
    clearDevices = "Limpiar", scanFailed = "Escaneo fallido", dismiss = "Descartar",
    scanningForDevices = "Buscando dispositivos mesh…",
    pressScanPrompt = "Presiona Escanear para descubrir dispositivos BLE cercanos",
    requiresBluetooth = "Requiere adaptador Bluetooth + BlueZ en ejecución",
    nickname = "Apodo", rename = "Renombrar", ping = "Ping", wave = "Ola",
    setNickname = "Establecer apodo", save = "Guardar", battery = "Batería", pair = "Emparejar…",
    // Network
    networkOverview = "Resumen de red", sent = "Enviados", received = "Recibidos",
    nearby = "Cercanos", ble = "BLE", bridgeRelay = "Puente de Retransmisión",
    connected = "● Conectado a", disconnected = "○ Desconectado",
    bridgeDisabled = "Puente desactivado", disconnect = "Desconectar", connect = "Conectar",
    visibleNodes = "Nodos visibles", found = "encontrados",
    noNodesVisible = "Sin nodos visibles — escanear en pestaña Dispositivos",
    lastSeen = "Visto por última vez:", readings = "lecturas",
    localNode = "Nodo local", rssiChart = "RSSI",
    // Packet Log
    packetLogTitle = "Registro de paquetes", clearLog = "Limpiar",
    filterAll = "Todos", filterInbound = "Entrada", filterOutbound = "Salida",
    noPackets = "Sin paquetes capturados.",
    // Topology
    topologyTitle = "Topología de malla", refreshLayout = "Actualizar",
    showLabels = "Etiquetas", noTopology = "Sin nodos visibles — escanear en pestaña Dispositivos",
    // Settings
    settingsTitle = "Ajustes", meshProtocol = "Protocolo de malla",
    defaultTtl = "TTL predeterminado", heartbeatInterval = "Intervalo de latido",
    maxReconnectAttempts = "Máx. intentos de reconexión", messageRetries = "Reintentos de mensaje",
    security = "Seguridad", e2eEncryption = "Cifrado extremo a extremo",
    e2eSubtitle = "ECDH P-256 + AES-256-GCM", bridge = "Puente",
    enableBridge = "Activar puente", bridgeSubtitle = "Reenviar paquetes vía WebSocket",
    bridgeServerUrl = "URL del servidor puente", bridgePlaceholder = "ws://localhost:8080/relay",
    appearance = "Apariencia", darkTheme = "Tema Oscuro",
    darkThemeSubtitle = "Alternar entre claro y oscuro", autoLock = "Bloqueo automático",
    enableAutoLock = "Activar bloqueo automático", autoLockSubtitle = "Bloquear tras inactividad",
    autoLockTimeout = "Bloquear después de", setPin = "Establecer PIN",
    changePin = "Cambiar PIN", clearPin = "Eliminar PIN", language = "Idioma",
    exportAll = "Exportar todas las conversaciones",
    exportAllSubtitle = "Volcar todos los mensajes a un archivo",
    exportedTo = "Exportado a",
    minutes = "min", enterPin = "Introducir PIN", confirmPin = "Confirmar PIN",
    pinsDoNotMatch = "Los PINs no coinciden", pinSet = "PIN establecido correctamente",
    wrongPin = "PIN incorrecto", attemptsRemaining = "intentos restantes",
    unlockApp = "Desbloquear TurboMesh",
    // Pairing
    pairingTitle = "Emparejamiento de clave", pairingStep1 = "1. Comparte tu clave pública",
    pairingStep2 = "2. Introduce la clave pública del par (Base64)",
    pairingStep3 = "3. Verifica que el PIN coincide en ambos dispositivos",
    pairingPin = "PIN de emparejamiento:", peerPublicKey = "Clave pública del par",
    peerKeyPlaceholder = "Pega la clave Base64…", pairingSuccess = "✓ ¡Emparejado!",
    pairingConfirm = "Confirmar emparejamiento", myPublicKey = "Mi clave pública",
    copyKey = "Copiar clave", copied = "¡Copiado!",
    derivePin = "Derivar PIN",
    pairingVerifyHint = "Verifica que este PIN coincida en el dispositivo par antes de confirmar.",
    shareClipboard = "Compartir portapapeles", clipboardSent = "Portapapeles enviado",
    fileAttachLabel = "Adjuntar archivo", fileReceived = "Archivo recibido",
    showInFolder = "Mostrar en carpeta", clipboardMessage = "Portapapeles",
    copyToClipboard = "Copiar",
    groups = "Grupos", newGroup = "Nuevo grupo", groupName = "Nombre del grupo",
    groupMembers = "Miembros", createGroup = "Crear grupo", deleteGroup = "Eliminar grupo",
    groupInviteSent = "Invitación de grupo enviada", noGroupsYet = "Sin grupos — ¡crea uno!",
    groupChat = "Grupo", scheduleAt = "Programar", scheduledFor = "Programado para",
    invalidDateTime = "Fecha/hora inválida — usa AAAA-MM-DD HH:MM",
    datePlaceholder = "AAAA-MM-DD", timePlaceholder = "HH:MM",
    messageExpiry = "Expira", noExpiry = "Nunca", expiry1h = "1 hora",
    expiry24h = "24 horas", expiry7d = "7 días", seenByCount = "Visto",
    online = "En línea", idle = "Inactivo", offline = "Sin conexión",
    markAllRead = "Marcar todo leído", clearConversation = "Limpiar conversación",
    conversationCleared = "Conversación eliminada",
)

val FrenchStrings = EnglishStrings.copy(
    // Tabs
    tabMessaging = "Messages", tabDevices = "Appareils", tabNetwork = "Réseau",
    tabSettings = "Paramètres", tabPacketLog = "Journal", tabTopology = "Topologie",
    // Messaging
    everyone = "Tout le monde", everyoneBroadcast = "Tout le monde (Diffusion)", toLabel = "À:",
    messagePlaceholder = "Message… (Entrée pour envoyer, Maj+Entrée nouvelle ligne)",
    send = "Envoyer", update = "Mettre à jour", emergency = "Urgence",
    search = "Rechercher", close = "Fermer", pinned = "Épinglés", export = "Exporter",
    noMessages = "Aucun message — envoyez quelque chose !",
    noMessagesMatch = "Aucun message correspondant", searchMessages = "Rechercher des messages…",
    clearLabel = "Effacer", pinnedMessages = "📌 Messages épinglés",
    replyingTo = "En réponse à :", editingMessage = "Modification du message",
    cancel = "Annuler", reply = "Répondre", react = "Réagir", edit = "Modifier",
    pin = "Épingler", unpin = "Désépingler", delete = "Supprimer",
    isTyping = "est en train d'écrire…", areTyping = "sont en train d'écrire…",
    // Devices
    bleDevices = "Appareils BLE", devicesFound = "appareils trouvés",
    deviceFound = "appareil trouvé", stopScan = "Arrêter", scan = "Scanner",
    clearDevices = "Effacer", scanFailed = "Échec du scan", dismiss = "Ignorer",
    scanningForDevices = "Recherche d'appareils mesh…",
    pressScanPrompt = "Appuyez sur Scanner pour découvrir des appareils BLE proches",
    requiresBluetooth = "Nécessite un adaptateur Bluetooth + BlueZ en cours d'exécution",
    nickname = "Surnom", rename = "Renommer", ping = "Ping", wave = "Saluer",
    setNickname = "Définir un surnom", save = "Sauvegarder", battery = "Batterie", pair = "Appairer…",
    // Network
    networkOverview = "Vue d'ensemble réseau", sent = "Envoyés", received = "Reçus",
    nearby = "À proximité", connected = "● Connecté à", disconnected = "○ Déconnecté",
    bridgeDisabled = "Pont désactivé", disconnect = "Déconnecter", connect = "Connecter",
    visibleNodes = "Nœuds visibles", found = "trouvés",
    noNodesVisible = "Aucun nœud visible — scanner dans l'onglet Appareils",
    lastSeen = "Vu pour la dernière fois :", localNode = "Nœud local",
    // Settings
    settingsTitle = "Paramètres", meshProtocol = "Protocole mesh",
    security = "Sécurité", bridge = "Pont", enableBridge = "Activer le pont",
    appearance = "Apparence", darkTheme = "Thème Sombre",
    darkThemeSubtitle = "Basculer entre clair et sombre",
    autoLock = "Verrouillage auto", enableAutoLock = "Activer le verrouillage auto",
    autoLockSubtitle = "Verrouiller après inactivité",
    setPin = "Définir PIN", changePin = "Modifier PIN", clearPin = "Supprimer PIN",
    language = "Langue", exportAll = "Tout Exporter",
    exportAllSubtitle = "Exporter tous les messages vers un fichier",
    exportedTo = "Exporté vers", minutes = "min",
    enterPin = "Saisir PIN", confirmPin = "Confirmer PIN",
    pinsDoNotMatch = "Les PINs ne correspondent pas", pinSet = "PIN défini avec succès",
    wrongPin = "PIN incorrect", attemptsRemaining = "tentatives restantes",
    unlockApp = "Déverrouiller TurboMesh",
    // Pairing
    pairingTitle = "Appairage de clé", pairingStep1 = "1. Partagez votre clé publique",
    pairingStep2 = "2. Entrez la clé publique du pair (Base64)",
    pairingStep3 = "3. Vérifiez que le PIN correspond sur les deux appareils",
    pairingPin = "PIN d'appairage :", peerPublicKey = "Clé publique du pair",
    peerKeyPlaceholder = "Coller la clé Base64…", pairingSuccess = "✓ Appairé !",
    pairingConfirm = "Confirmer l'appairage", myPublicKey = "Ma clé publique",
    copyKey = "Copier la clé", copied = "Copié !",
    derivePin = "Dériver le PIN",
    pairingVerifyHint = "Vérifiez que ce PIN correspond sur l'appareil pair avant de confirmer.",
    shareClipboard = "Partager le presse-papiers", clipboardSent = "Presse-papiers envoyé",
    fileAttachLabel = "Joindre un fichier", fileReceived = "Fichier reçu",
    showInFolder = "Afficher dans le dossier", clipboardMessage = "Presse-papiers",
    copyToClipboard = "Copier",
    groups = "Groupes", newGroup = "Nouveau groupe", groupName = "Nom du groupe",
    groupMembers = "Membres", createGroup = "Créer un groupe", deleteGroup = "Supprimer le groupe",
    groupInviteSent = "Invitation de groupe envoyée", noGroupsYet = "Aucun groupe — créez-en un !",
    groupChat = "Groupe", scheduleAt = "Planifier", scheduledFor = "Planifié pour",
    invalidDateTime = "Date/heure invalide — utilisez AAAA-MM-JJ HH:MM",
    datePlaceholder = "AAAA-MM-JJ", timePlaceholder = "HH:MM",
    messageExpiry = "Expire", noExpiry = "Jamais", expiry1h = "1 heure",
    expiry24h = "24 heures", expiry7d = "7 jours", seenByCount = "Vu",
    online = "En ligne", idle = "Inactif", offline = "Hors ligne",
    markAllRead = "Tout marquer comme lu", clearConversation = "Effacer la conversation",
    conversationCleared = "Conversation effacée",
)

val GermanStrings = EnglishStrings.copy(
    // Tabs
    tabMessaging = "Nachrichten", tabDevices = "Geräte", tabNetwork = "Netzwerk",
    tabSettings = "Einstellungen", tabPacketLog = "Protokoll", tabTopology = "Topologie",
    // Messaging
    everyone = "Alle", everyoneBroadcast = "Alle (Broadcast)", toLabel = "An:",
    messagePlaceholder = "Nachricht… (Enter zum Senden, Umschalt+Enter neue Zeile)",
    send = "Senden", update = "Aktualisieren", emergency = "Notfall",
    search = "Suchen", close = "Schließen", pinned = "Angeheftet", export = "Exportieren",
    noMessages = "Keine Nachrichten — sende etwas!", noMessagesMatch = "Keine Treffer",
    searchMessages = "Nachrichten suchen…", clearLabel = "Löschen",
    pinnedMessages = "📌 Angeheftete Nachrichten", replyingTo = "Antwort auf:",
    editingMessage = "Nachricht bearbeiten", cancel = "Abbrechen",
    reply = "Antworten", react = "Reagieren", edit = "Bearbeiten",
    pin = "Anheften", unpin = "Loslösen", delete = "Löschen",
    isTyping = "tippt…", areTyping = "tippen…",
    // Devices
    bleDevices = "BLE-Geräte", devicesFound = "Geräte gefunden",
    deviceFound = "Gerät gefunden", stopScan = "Stoppen", scan = "Scannen",
    clearDevices = "Leeren", scanFailed = "Scan fehlgeschlagen", dismiss = "Verwerfen",
    scanningForDevices = "Suche nach Mesh-Geräten…",
    pressScanPrompt = "Drücke Scannen, um BLE-Geräte in der Nähe zu entdecken",
    requiresBluetooth = "Erfordert Bluetooth-Adapter + laufendes BlueZ",
    nickname = "Spitzname", rename = "Umbenennen", ping = "Ping", wave = "Winken",
    setNickname = "Spitznamen setzen", save = "Speichern", battery = "Akku", pair = "Koppeln…",
    // Network
    networkOverview = "Netzwerkübersicht", sent = "Gesendet", received = "Empfangen",
    nearby = "In der Nähe", connected = "● Verbunden mit", disconnected = "○ Getrennt",
    bridgeDisabled = "Bridge deaktiviert", disconnect = "Trennen", connect = "Verbinden",
    visibleNodes = "Sichtbare Knoten", found = "gefunden",
    noNodesVisible = "Keine Knoten sichtbar — im Tab Geräte scannen",
    lastSeen = "Zuletzt gesehen:", localNode = "Lokaler Knoten",
    // Settings
    settingsTitle = "Einstellungen", meshProtocol = "Mesh-Protokoll",
    security = "Sicherheit", bridge = "Bridge", enableBridge = "Bridge aktivieren",
    appearance = "Erscheinungsbild", darkTheme = "Dunkles Design",
    darkThemeSubtitle = "Zwischen hell und dunkel umschalten",
    autoLock = "Automatische Sperre", enableAutoLock = "Auto-Sperre aktivieren",
    autoLockSubtitle = "App nach Inaktivität sperren",
    setPin = "PIN setzen", changePin = "PIN ändern", clearPin = "PIN löschen",
    language = "Sprache", exportAll = "Alles Exportieren",
    exportAllSubtitle = "Alle Nachrichten in Datei exportieren",
    exportedTo = "Exportiert nach", minutes = "Min",
    enterPin = "PIN eingeben", confirmPin = "PIN bestätigen",
    pinsDoNotMatch = "PINs stimmen nicht überein", pinSet = "PIN erfolgreich gesetzt",
    wrongPin = "Falscher PIN", attemptsRemaining = "Versuche verbleibend",
    unlockApp = "TurboMesh entsperren",
    // Pairing
    pairingTitle = "Schlüssel-Kopplung", pairingStep1 = "1. Öffentlichen Schlüssel teilen",
    pairingStep2 = "2. Öffentlichen Schlüssel des Peers eingeben (Base64)",
    pairingStep3 = "3. PIN auf beiden Geräten vergleichen",
    pairingPin = "Kopplungs-PIN:", peerPublicKey = "Öffentlicher Schlüssel des Peers",
    peerKeyPlaceholder = "Base64-Schlüssel einfügen…", pairingSuccess = "✓ Gekoppelt!",
    pairingConfirm = "Kopplung bestätigen", myPublicKey = "Mein öffentlicher Schlüssel",
    copyKey = "Schlüssel kopieren", copied = "Kopiert!",
    derivePin = "PIN ableiten",
    pairingVerifyHint = "Vergewissere dich, dass dieser PIN auf dem Peer-Gerät übereinstimmt.",
    shareClipboard = "Zwischenablage teilen", clipboardSent = "Zwischenablage gesendet",
    fileAttachLabel = "Datei anhängen", fileReceived = "Datei empfangen",
    showInFolder = "Im Ordner anzeigen", clipboardMessage = "Zwischenablage",
    copyToClipboard = "Kopieren",
    groups = "Gruppen", newGroup = "Neue Gruppe", groupName = "Gruppenname",
    groupMembers = "Mitglieder", createGroup = "Gruppe erstellen", deleteGroup = "Gruppe löschen",
    groupInviteSent = "Gruppeneinladung gesendet", noGroupsYet = "Keine Gruppen — erstelle eine!",
    groupChat = "Gruppe", scheduleAt = "Planen", scheduledFor = "Geplant für",
    invalidDateTime = "Ungültige Datum/Zeit — benutze JJJJ-MM-TT HH:MM",
    datePlaceholder = "JJJJ-MM-TT", timePlaceholder = "HH:MM",
    messageExpiry = "Läuft ab", noExpiry = "Nie", expiry1h = "1 Stunde",
    expiry24h = "24 Stunden", expiry7d = "7 Tage", seenByCount = "Gesehen",
    online = "Online", idle = "Inaktiv", offline = "Offline",
    markAllRead = "Alle als gelesen markieren", clearConversation = "Gespräch löschen",
    conversationCleared = "Gespräch gelöscht",
)

val JapaneseStrings = EnglishStrings.copy(
    // Tabs
    tabMessaging = "メッセージ", tabDevices = "デバイス", tabNetwork = "ネットワーク",
    tabSettings = "設定", tabPacketLog = "パケットログ", tabTopology = "トポロジー",
    // Messaging
    everyone = "全員", everyoneBroadcast = "全員（ブロードキャスト）", toLabel = "宛先:",
    messagePlaceholder = "メッセージ…（Enterで送信、Shift+Enterで改行）",
    send = "送信", update = "更新", emergency = "緊急",
    search = "検索", close = "閉じる", pinned = "ピン留め", export = "エクスポート",
    noMessages = "メッセージなし — 何か送信してください！",
    noMessagesMatch = "一致するメッセージなし", searchMessages = "メッセージを検索…",
    clearLabel = "クリア", pinnedMessages = "📌 ピン留めメッセージ",
    replyingTo = "返信先:", editingMessage = "メッセージを編集中",
    cancel = "キャンセル", reply = "返信", react = "リアクション", edit = "編集",
    pin = "ピン留め", unpin = "ピン解除", delete = "削除",
    isTyping = "が入力中…", areTyping = "が入力中…",
    // Devices
    bleDevices = "BLEデバイス", devicesFound = "台のデバイスが見つかりました",
    deviceFound = "台のデバイスが見つかりました", stopScan = "停止", scan = "スキャン",
    clearDevices = "クリア", scanFailed = "スキャン失敗", dismiss = "閉じる",
    scanningForDevices = "メッシュデバイスを検索中…",
    pressScanPrompt = "スキャンを押して近くのBLEデバイスを発見する",
    requiresBluetooth = "Bluetoothアダプター + BlueZ が必要です",
    nickname = "ニックネーム", rename = "名前変更", ping = "Ping", wave = "挨拶",
    setNickname = "ニックネームを設定", save = "保存", battery = "バッテリー", pair = "ペアリング…",
    // Network
    networkOverview = "ネットワーク概要", sent = "送信済み", received = "受信済み",
    nearby = "近くのノード", connected = "● 接続中:", disconnected = "○ 切断",
    bridgeDisabled = "ブリッジ無効", disconnect = "切断", connect = "接続",
    visibleNodes = "表示中のノード", found = "台発見",
    noNodesVisible = "ノードなし — デバイスタブでスキャン",
    lastSeen = "最終確認:", localNode = "ローカルノード",
    // Settings
    settingsTitle = "設定", meshProtocol = "メッシュプロトコル",
    security = "セキュリティ", bridge = "ブリッジ", enableBridge = "ブリッジを有効にする",
    appearance = "外観", darkTheme = "ダークテーマ",
    darkThemeSubtitle = "ライト/ダークテーマの切り替え",
    autoLock = "自動ロック", enableAutoLock = "自動ロックを有効にする",
    autoLockSubtitle = "非アクティブ後にロック",
    setPin = "PINを設定", changePin = "PINを変更", clearPin = "PINを削除",
    language = "言語", exportAll = "全会話をエクスポート",
    exportAllSubtitle = "すべてのメッセージをテキストファイルに出力",
    exportedTo = "エクスポート先", minutes = "分",
    enterPin = "PINを入力", confirmPin = "PINを確認",
    pinsDoNotMatch = "PINが一致しません", pinSet = "PINが正常に設定されました",
    wrongPin = "PINが正しくありません", attemptsRemaining = "回残っています",
    unlockApp = "TurboMeshのロックを解除",
    // Pairing
    pairingTitle = "鍵のペアリング", pairingStep1 = "1. 公開鍵を共有する",
    pairingStep2 = "2. 相手の公開鍵を入力（Base64）",
    pairingStep3 = "3. 両デバイスでPINが一致することを確認",
    pairingPin = "ペアリングPIN:", peerPublicKey = "相手の公開鍵",
    peerKeyPlaceholder = "Base64鍵を貼り付け…", pairingSuccess = "✓ ペアリング完了！",
    pairingConfirm = "ペアリングを確認", myPublicKey = "自分の公開鍵",
    copyKey = "鍵をコピー", copied = "コピーしました！",
    derivePin = "PINを導出",
    pairingVerifyHint = "確認前に相手デバイスでPINが一致していることを確認してください。",
    shareClipboard = "クリップボードを共有", clipboardSent = "クリップボードを送信しました",
    fileAttachLabel = "ファイルを添付", fileReceived = "ファイルを受信しました",
    showInFolder = "フォルダに表示", clipboardMessage = "クリップボード",
    copyToClipboard = "コピー",
    groups = "グループ", newGroup = "新しいグループ", groupName = "グループ名",
    groupMembers = "メンバー", createGroup = "グループを作成", deleteGroup = "グループを削除",
    groupInviteSent = "グループ招待を送信しました", noGroupsYet = "グループなし — 作成してください！",
    groupChat = "グループ", scheduleAt = "スケジュール", scheduledFor = "予定時刻",
    invalidDateTime = "無効な日時 — YYYY-MM-DD HH:MM を使用してください",
    datePlaceholder = "YYYY-MM-DD", timePlaceholder = "HH:MM",
    messageExpiry = "有効期限", noExpiry = "なし", expiry1h = "1時間",
    expiry24h = "24時間", expiry7d = "7日間", seenByCount = "既読",
    online = "オンライン", idle = "アイドル", offline = "オフライン",
    markAllRead = "すべて既読にする", clearConversation = "会話をクリア",
    conversationCleared = "会話をクリアしました",
)

val LocalStrings = compositionLocalOf { EnglishStrings }

fun languageToStrings(lang: String): AppStrings = when (lang) {
    "es" -> SpanishStrings
    "fr" -> FrenchStrings
    "de" -> GermanStrings
    "ja" -> JapaneseStrings
    else -> EnglishStrings
}

val languageOptions = listOf(
    "en" to "English",
    "es" to "Español",
    "fr" to "Français",
    "de" to "Deutsch",
    "ja" to "日本語",
)
