package com.turbomesh.desktop.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Tabs
    val tabMessaging: String,
    val tabDevices: String,
    val tabNetwork: String,
    val tabSettings: String,
    val tabPacketLog: String,
    val tabTopology: String,
    // Messaging
    val everyone: String,
    val everyoneBroadcast: String,
    val toLabel: String,
    val messagePlaceholder: String,
    val send: String,
    val update: String,
    val emergency: String,
    val search: String,
    val close: String,
    val pinned: String,
    val export: String,
    val noMessages: String,
    val noMessagesMatch: String,
    val searchMessages: String,
    val clearLabel: String,
    val pinnedMessages: String,
    val results: String,
    val result: String,
    val forText: String,
    val replyingTo: String,
    val editingMessage: String,
    val cancel: String,
    val reply: String,
    val react: String,
    val edit: String,
    val pin: String,
    val unpin: String,
    val delete: String,
    val isTyping: String,
    val areTyping: String,
    val schedule: String,
    val attachFile: String,
    val voiceNote: String,
    val seenBy: String,
    val scheduleMessage: String,
    val scheduleDate: String,
    val scheduleTime: String,
    val confirm: String,
    val pendingScheduled: String,
    val fileAttached: String,
    val voiceRecording: String,
    val playVoice: String,
    val stopVoice: String,
    // Devices
    val bleDevices: String,
    val devicesFound: String,
    val deviceFound: String,
    val stopScan: String,
    val scan: String,
    val clearDevices: String,
    val scanFailed: String,
    val dismiss: String,
    val scanningForDevices: String,
    val pressScanPrompt: String,
    val requiresBluetooth: String,
    val nickname: String,
    val rename: String,
    val ping: String,
    val wave: String,
    val setNickname: String,
    val save: String,
    val battery: String,
    val pair: String,
    // Network
    val networkOverview: String,
    val sent: String,
    val received: String,
    val nearby: String,
    val ble: String,
    val bridgeRelay: String,
    val connected: String,
    val disconnected: String,
    val bridgeDisabled: String,
    val disconnect: String,
    val connect: String,
    val visibleNodes: String,
    val found: String,
    val noNodesVisible: String,
    val lastSeen: String,
    val readings: String,
    val localNode: String,
    val rssiChart: String,
    // Packet Log
    val packetLogTitle: String,
    val clearLog: String,
    val filterAll: String,
    val filterInbound: String,
    val filterOutbound: String,
    val noPackets: String,
    val bytes: String,
    val hops: String,
    // Topology
    val topologyTitle: String,
    val refreshLayout: String,
    val showLabels: String,
    val noTopology: String,
    // Settings
    val settingsTitle: String,
    val meshProtocol: String,
    val defaultTtl: String,
    val heartbeatInterval: String,
    val maxReconnectAttempts: String,
    val messageRetries: String,
    val security: String,
    val e2eEncryption: String,
    val e2eSubtitle: String,
    val bridge: String,
    val enableBridge: String,
    val bridgeSubtitle: String,
    val bridgeServerUrl: String,
    val bridgePlaceholder: String,
    val appearance: String,
    val darkTheme: String,
    val darkThemeSubtitle: String,
    val autoLock: String,
    val enableAutoLock: String,
    val autoLockSubtitle: String,
    val autoLockTimeout: String,
    val setPin: String,
    val changePin: String,
    val clearPin: String,
    val language: String,
    val exportAll: String,
    val exportAllSubtitle: String,
    val exportedTo: String,
    val appVersion: String,
    val appSubtitle: String,
    val minutes: String,
    val enterPin: String,
    val confirmPin: String,
    val pinsDoNotMatch: String,
    val pinSet: String,
    val wrongPin: String,
    val attemptsRemaining: String,
    val unlockApp: String,
    // Pairing
    val pairingTitle: String,
    val pairingStep1: String,
    val pairingStep2: String,
    val pairingStep3: String,
    val pairingPin: String,
    val peerPublicKey: String,
    val peerKeyPlaceholder: String,
    val pairingSuccess: String,
    val pairingConfirm: String,
    val myPublicKey: String,
    val copyKey: String,
    val copied: String,
)

val EnglishStrings = AppStrings(
    tabMessaging = "Messaging", tabDevices = "Devices", tabNetwork = "Network",
    tabSettings = "Settings", tabPacketLog = "Packet Log", tabTopology = "Topology",
    everyone = "Everyone", everyoneBroadcast = "Everyone (Broadcast)", toLabel = "To:",
    messagePlaceholder = "Message… (Enter to send, Shift+Enter newline)",
    send = "Send", update = "Update", emergency = "Emergency", search = "Search",
    close = "Close", pinned = "Pinned", export = "Export", noMessages = "No messages yet — send something!",
    noMessagesMatch = "No messages match", searchMessages = "Search messages…", clearLabel = "Clear",
    pinnedMessages = "📌 Pinned Messages", results = "results", result = "result", forText = "for",
    replyingTo = "Replying to:", editingMessage = "Editing message", cancel = "Cancel",
    reply = "Reply", react = "React", edit = "Edit", pin = "Pin", unpin = "Unpin", delete = "Delete",
    isTyping = "is typing…", areTyping = "are typing…", schedule = "Schedule", attachFile = "Attach File",
    voiceNote = "Voice Note", seenBy = "Seen by", scheduleMessage = "Schedule Message",
    scheduleDate = "Date (YYYY-MM-DD)", scheduleTime = "Time (HH:MM)", confirm = "Confirm",
    pendingScheduled = "⏰ Scheduled", fileAttached = "📎 File", voiceRecording = "Recording…",
    playVoice = "▶ Play", stopVoice = "■ Stop",
    bleDevices = "BLE Devices", devicesFound = "devices found", deviceFound = "device found",
    stopScan = "Stop", scan = "Scan", clearDevices = "Clear", scanFailed = "Scan failed",
    dismiss = "Dismiss", scanningForDevices = "Scanning for mesh devices…",
    pressScanPrompt = "Press Scan to discover nearby BLE devices",
    requiresBluetooth = "Requires Bluetooth adapter + BlueZ running",
    nickname = "Nickname", rename = "Rename", ping = "Ping", wave = "Wave",
    setNickname = "Set Nickname", save = "Save", battery = "Battery", pair = "Pair…",
    networkOverview = "Network Overview", sent = "Sent", received = "Received",
    nearby = "Nearby", ble = "BLE", bridgeRelay = "Bridge Relay", connected = "● Connected to",
    disconnected = "○ Disconnected", bridgeDisabled = "Bridge disabled",
    disconnect = "Disconnect", connect = "Connect", visibleNodes = "Visible Nodes",
    found = "found", noNodesVisible = "No nodes visible — scan from Devices tab",
    lastSeen = "Last seen:", readings = "readings", localNode = "Local Node", rssiChart = "RSSI",
    packetLogTitle = "Packet Log", clearLog = "Clear", filterAll = "All",
    filterInbound = "Inbound", filterOutbound = "Outbound", noPackets = "No packets captured yet.",
    bytes = "B", hops = "hops",
    topologyTitle = "Mesh Topology", refreshLayout = "Refresh", showLabels = "Labels",
    noTopology = "No nodes visible — scan from Devices tab",
    settingsTitle = "Settings", meshProtocol = "Mesh Protocol", defaultTtl = "Default TTL",
    heartbeatInterval = "Heartbeat interval", maxReconnectAttempts = "Max reconnect attempts",
    messageRetries = "Message retries", security = "Security",
    e2eEncryption = "End-to-End Encryption", e2eSubtitle = "ECDH P-256 + AES-256-GCM",
    bridge = "Bridge", enableBridge = "Enable Bridge",
    bridgeSubtitle = "Forward packets via WebSocket relay",
    bridgeServerUrl = "Bridge Server URL", bridgePlaceholder = "ws://localhost:8080/relay",
    appearance = "Appearance", darkTheme = "Dark Theme", darkThemeSubtitle = "Toggle between light and dark",
    autoLock = "Auto-Lock", enableAutoLock = "Enable Auto-Lock",
    autoLockSubtitle = "Lock app after inactivity",
    autoLockTimeout = "Lock after", setPin = "Set PIN", changePin = "Change PIN",
    clearPin = "Clear PIN", language = "Language", exportAll = "Export All Conversations",
    exportAllSubtitle = "Dump all messages to a text file",
    exportedTo = "Exported to", appVersion = "TurboMesh Desktop",
    appSubtitle = "Compose Multiplatform • BLE Mesh over BlueZ",
    minutes = "min", enterPin = "Enter PIN", confirmPin = "Confirm PIN",
    pinsDoNotMatch = "PINs do not match", pinSet = "PIN set successfully",
    wrongPin = "Incorrect PIN", attemptsRemaining = "attempts remaining",
    unlockApp = "Unlock TurboMesh",
    pairingTitle = "Key Pairing", pairingStep1 = "1. Share your public key",
    pairingStep2 = "2. Enter peer's public key (hex/Base64)",
    pairingStep3 = "3. Verify pairing PIN matches on both devices",
    pairingPin = "Pairing PIN:", peerPublicKey = "Peer Public Key",
    peerKeyPlaceholder = "Paste Base64 key…", pairingSuccess = "✓ Paired!",
    pairingConfirm = "Confirm Pair", myPublicKey = "My Public Key",
    copyKey = "Copy Key", copied = "Copied!",
)

val SpanishStrings = EnglishStrings.copy(
    tabMessaging = "Mensajes", tabDevices = "Dispositivos", tabNetwork = "Red",
    tabSettings = "Ajustes", tabPacketLog = "Registro", tabTopology = "Topología",
    everyone = "Todos", send = "Enviar", search = "Buscar", close = "Cerrar",
    cancel = "Cancelar", save = "Guardar", scan = "Escanear", stopScan = "Detener",
    connect = "Conectar", disconnect = "Desconectar", settingsTitle = "Ajustes",
    darkTheme = "Tema Oscuro", language = "Idioma", exportAll = "Exportar Todo",
    enableAutoLock = "Bloqueo Automático", unlockApp = "Desbloquear TurboMesh",
    wrongPin = "PIN incorrecto", pairingTitle = "Emparejamiento de Clave",
)

val FrenchStrings = EnglishStrings.copy(
    tabMessaging = "Messages", tabDevices = "Appareils", tabNetwork = "Réseau",
    tabSettings = "Paramètres", tabPacketLog = "Journal", tabTopology = "Topologie",
    everyone = "Tout le monde", send = "Envoyer", search = "Rechercher", close = "Fermer",
    cancel = "Annuler", save = "Sauvegarder", scan = "Scanner", stopScan = "Arrêter",
    connect = "Connecter", disconnect = "Déconnecter", settingsTitle = "Paramètres",
    darkTheme = "Thème Sombre", language = "Langue", exportAll = "Tout Exporter",
    enableAutoLock = "Verrouillage Auto", unlockApp = "Déverrouiller TurboMesh",
    wrongPin = "PIN incorrect", pairingTitle = "Appairage de Clé",
)

val GermanStrings = EnglishStrings.copy(
    tabMessaging = "Nachrichten", tabDevices = "Geräte", tabNetwork = "Netzwerk",
    tabSettings = "Einstellungen", tabPacketLog = "Protokoll", tabTopology = "Topologie",
    everyone = "Alle", send = "Senden", search = "Suchen", close = "Schließen",
    cancel = "Abbrechen", save = "Speichern", scan = "Scannen", stopScan = "Stoppen",
    connect = "Verbinden", disconnect = "Trennen", settingsTitle = "Einstellungen",
    darkTheme = "Dunkles Design", language = "Sprache", exportAll = "Alles Exportieren",
    enableAutoLock = "Auto-Sperre", unlockApp = "TurboMesh Entsperren",
    wrongPin = "Falscher PIN", pairingTitle = "Schlüssel-Kopplung",
)

val JapaneseStrings = EnglishStrings.copy(
    tabMessaging = "メッセージ", tabDevices = "デバイス", tabNetwork = "ネットワーク",
    tabSettings = "設定", tabPacketLog = "パケットログ", tabTopology = "トポロジー",
    everyone = "全員", send = "送信", search = "検索", close = "閉じる",
    cancel = "キャンセル", save = "保存", scan = "スキャン", stopScan = "停止",
    connect = "接続", disconnect = "切断", settingsTitle = "設定",
    darkTheme = "ダークテーマ", language = "言語", exportAll = "全会話をエクスポート",
    enableAutoLock = "自動ロック", unlockApp = "TurboMeshのロック解除",
    wrongPin = "PINが正しくありません", pairingTitle = "鍵のペアリング",
)

val LocalStrings = compositionLocalOf { EnglishStrings }

fun languageToStrings(lang: String): AppStrings = when (lang) {
    "es" -> SpanishStrings
    "fr" -> FrenchStrings
    "de" -> GermanStrings
    "ja" -> JapaneseStrings
    else -> EnglishStrings
}

val languageOptions = listOf(
    "en" to "English",
    "es" to "Español",
    "fr" to "Français",
    "de" to "Deutsch",
    "ja" to "日本語",
)
